### ISSUE TITLE
Inconsistent return values in LoadBalancerPool

### ISSUE THREAD

**Issue by jr2730** [DimensionDataResearch/ansible-modules-extras#3]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

cloud/DimensionData/dimensiondata_load_balancer_pool.py
##### ANSIBLE VERSION

doesn't matter
##### CONFIGURATION

doesn't matter
##### OS / ENVIRONMENT

doesn't matter
##### SUMMARY

Returns different status values depending on whether LB Pool already exists or not.
Yes, it probably should but I don't think it should like this.

Following is output from my code when pool **DOES NOT EXIST**:

task path: /home/vagrant/common/ansible-testing/dd-tests/tasks/main.yml:18

ok: [localhost] => {
    "the_pool": {
        "changed": true,
        "load_balancer_pool": {
            "description": "a pool yo",
            "health_monitor_id": null,
            "id": "d2fb4cf9-ef82-4506-a1f3-5d22c6385edd",
            "load_balance_method": "ROUND_ROBIN",
            "name": "lb_pool_name",
            "service_down_action": "DROP",
            "slow_ramp_time": "23",
            **"status": 0**
        },
        **"msg": "Success."**
    }
}

And here is the same code when the LB Pool **already exists**:

task path: /home/vagrant/common/ansible-testing/dd-tests/tasks/main.yml:18
ok: [localhost] => {
    "the_pool": {
        "changed": false,
        "load_balancer_pool": {
            "description": "a pool yo",
            "health_monitor_id": null,
            "id": "d2fb4cf9-ef82-4506-a1f3-5d22c6385edd",
            "load_balance_method": "ROUND_ROBIN",
            "name": "lb_pool_name",
            "service_down_action": "DROP",
            "slow_ramp_time": "23",
            **"status": "NORMAL"**
        },
        **"msg": "Load balancer pool already exists."**
    }
}

I totally agree that the msg should be different.
But I believe that having one int status and one string status (and with both seeming to mean GOOD) is confusing.
##### STEPS TO REPRODUCE

```
   # create pool (as needed)
    - name: Create Load Balancer Pool (as needed)
      dimensiondata_load_balancer_pool:
        region: "{{ dd_tests_region }}"
        location: "{{ dd_tests_location }}"
        network_domain: "{{ dd_tests_network }}"
        name: "{{ dd_tests_lb_pool_name }}"
        description: a pool yo
        load_balance_method: ROUND_ROBIN
        health_monitor_1: Http
        health_monitor_2: Tcp
        service_down_action: DROP
        slow_ramp_time: 23
        ensure: present
      ignore_errors: yes
      register: the_pool
    - debug: var=the_pool verbosity=3
```

@aimonb , @relaxdiego : Thoughts??

**Comment by aimonb** [comment]
This is a bi-product of the ensure statement. We are ensuring a state present or absent. The exit 'changed' value must be set to true only if something has changed.  The message itself is designed for a human reader, not parsed. If the user does not have ansi color in the terminal, the conext of green vs yellow output will not be seen.  So the message is different for created vs already exists.
